version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pablo
      POSTGRES_PASSWORD: pablo
      POSTGRES_DB: api
    volumes:
      - data-url:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data-url: